import pandas as pd
import matplotlib.pyplot as plt
import os
import sys

# Path to the CSV file generated by the C program
csv_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "build", "fitness.csv")

# Fallback: check if it's in the current directory instead of build
if not os.path.exists(csv_path):
    csv_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fitness.csv")

if not os.path.exists(csv_path):
    print(f"Error: Could not find fitness data at {csv_path}")
    print("Make sure you have run the training executable first to generate the CSV.")
    sys.exit(1)

print(f"Loading fitness data from: {csv_path}")

try:
    # Read the CSV file using pandas
    df = pd.read_csv(csv_path)
    
    # Check if the required columns exist
    if not {'Generation', 'AverageFitness', 'MaxFitness'}.issubset(df.columns):
        print("Error: The CSV file does not contain the expected columns.")
        print(f"Found columns: {list(df.columns)}")
        sys.exit(1)

    # Create the plot
    plt.figure(figsize=(10, 6))
    plt.plot(df['Generation'], df['MaxFitness'], label='Max Fitness', color='green', linewidth=2)
    plt.plot(df['Generation'], df['AverageFitness'], label='Average Fitness', color='blue', linewidth=1.5, alpha=0.8)

    plt.xlabel('Generation')
    plt.ylabel('Fitness')
    plt.title('Evolutionary Strategy Training Progress')
    plt.legend()
    plt.grid(True)
    
    # Show the plot
    plt.tight_layout()
    plt.show()

except Exception as e:
    print(f"An error occurred while plotting: {e}")
